### ISSUE TITLE
Where are the examples?

### ISSUE THREAD

**Issue by olafleur** [db48x/emularity#1]
The examples are not in the repo. Is that normal?

I am not able to run one example because of that.

Thanks for that awesome piece of technology!

**Comment by db48x** [comment]
There are some arcade roms at http://www.mamedev.org/roms/ you could test with. I should get some shareware for the dosbox example...

**Comment by olafleur** [comment]
Yeah. I would like to get the dosbox example working.

My objective is to run an old .com file which run perfectly fine in dosbox, but I am not able to make it run in Dosbox's emulator. That's why I want to try with one of the examples, to see if the problem is my browser or the config that I do.

**Comment by db48x** [comment]
Ok, I changed the dosbox example from ZZT to DOOM, and included the shareware version in the repository (well, annexed it at any rate). This should help, and it shows off one of the quirks of the dosbox-sync emulator.
