### ISSUE TITLE
Improve coding style/formatting

### ISSUE THREAD

**Issue by n0samu** [db48x/emularity#105]
loader.js seems to follow no consistent formatting rules. I'd be happy to run a formatter/linter on it if you are fine with that. The lack of consistent formatting throws off my text editor and makes the code difficult to work with.

**Comment by db48x** [comment]
It’s not perfectly consistent, but it does mostly follow a style. That style is fairly eccentric to most eyes, but I like it. The main thing is to align long argument lists vertically, and to indent the content of object literals and functions relative to their starting positions. Consider these two ways of calling this hypothetical function with three arguments:

```javascript
doTheThing(42, {
  foo: 24,
  bar: 4224,
}, function acallback() {
  console.log("callback called");
});
```

vs

```javascript
doTheThing(42,
           {
             foo: 24,
             bar: 4224,
           },
           function acallback() {
             console.log("callback called");
           });
```

The latter is much preferred, as the indentation of the object literal and function arguments does not break up the vertical alignment of the argument list.
