### ISSUE TITLE
Unable to load needed sound file for CPS2 games

### ISSUE THREAD

**Issue by gitguudd** [db48x/emularity#111]
Just a question -- I have a some CPS2 roms that require a separate file to be loaded in MAME.

I've used emscripten to generate a javascript version of MAME 0.271 but when loading a CPS2 rom (in this case, Marvel Vs Capcom: Clash of the Super Heroes) it's complaining about a missing `dl-1425.bin` file.

I have a copy of the file, but I'm finding myself unable to tell the emulator it exists.

My index.html javascript looks like this:

```
<script type="text/javascript">
      var emulator = new Emulator(document.querySelector("#canvas"),
                                  null,
                                  new JSMAMELoader(JSMAMELoader.driver("mvscur1"),
                                                   JSMAMELoader.nativeResolution(256,256),
                                                   JSMAMELoader.scale(3),
                                                   JSMAMELoader.emulatorWASM('capcom.wasm'),
                                                   JSMAMELoader.mountFile("mvscur1.zip",
                                                                          JSMAMELoader.fetchFile("Marvel Vs Capcom",
                                                                                                 "mvscur1.zip")),
                                                   JSMAMELoader.mountFile("sound", JSMAMELoader.fetchFile("sound", "qsound_hle.zip")),
                                                   JSMAMELoader.peripheral("sound", "qsound_hle.zip")
                                                  ));
      emulator.start({ waitAfterDownloading: true });
    </script>
```

and the error code I'm getting is `dl-1425.bin NOT FOUND (tried in qsound_hle mvscur1 mvsc)`.

My folder structure for the roms is pretty simple like this:

```
\
|--index.html
|-- emu\
       |
       |-- capcom.js
|-- roms\
        |
        |--mvsc.zip
```

Is there something I'm missing?

**Comment by db48x** [comment]
I don’t know enough about MAME to advise  you, but the error message looks to me like it’s looking for a file named “dl-1425.bin”. If that exists inside the `qsound_hle.zip` file that you are downloading, then it may need that zip file to be decompressed first. You can do that by using `mountZip` instead of `mountFile`.
