### ISSUE TITLE
emularity API Questions

### ISSUE THREAD

**Issue by veso266** [db48x/emularity#14]
Hi I would like to know how can I use Runtime API found at TEHNICAL.md (what's the difrence between toggleMute() and mute(), unmute()) I would also like to know what does setSplashColors() do? (does it set custom image instead of emularity logo? (if not how can I do that?) 

Thanks for Anwsering and Best Regards

**Comment by db48x** [comment]
`mute` silences the audio, and `unmute` restores it. `toggleMute` silences the audio if it's playing, and restores it if it's muted.

`setSplashColors` is a bit of a hack. It just lets you change the foreground, background, and error colors used by the splash screen:

    emulator.setSplashColors({ foreground: 'white',
                               background: 'black',
                               failure: 'red' });

This is a hold-over from several years ago, when the splash screen was done by drawing on the canvas element itself. I soon rewrite it to use normal html to create the splash screen, but didn't change the interface. It should probably be using CSS classes that you could style, but that has some interesting problems of its own and there have always been more important things to work on.

I hope this helps!
