### ISSUE TITLE
Sound lag

### ISSUE THREAD

**Issue by dosboxonline** [db48x/emularity#15]
Sound lag(delay) all drivers and browsers. Or it's a question for the MAME developers? Thanks.
Example:
https://dosboxonline.github.io/games90s/segams/ninja-gaiden.html
https://dosboxonline.github.io/games90s/gamegear/arena-maze-of-death.html
es6, browser, loader files from this repo.

**Comment by db48x** [comment]
I've not noticed any audio lag myself. Audio emulation is generally quite CPU-intensive, though, so it may happen on slower computers.

**Comment by dosboxonline** [comment]
Ok!
