### ISSUE TITLE
Failed to load resource: the server responded with a status of dosbox-sync.js.gz 404 (Not Found)

### ISSUE THREAD

**Issue by phantompepper** [db48x/emularity#19]
While trying the EM-DOSBOX example on on my website, I am getting the following error in the console (Chrome 32bit)

`Failed to load resource: the server responded with a status of dosbox-sync.js.gz 404 (Not Found)`

Any help in solving this would be great. I'm assuming the GZ folder needs extracted?

**Comment by phantompepper** [comment]
If GZ needs to be extracted, how would I go about that?

**Comment by johnnyl** [comment]
tar -xvzf dosbox-sync.js.gz

**Comment by db48x** [comment]
Yes, the examples all want uncompressed JS files; the names are an artifact of how IA has their servers set up which I should clean up. I do recommend setting up your web server to use compression on transport, but it doesn't usually involve precompressing the file manually.
