### ISSUE TITLE
Bring all the mame drivers to the same version

### ISSUE THREAD

**Issue by bfod** [db48x/emularity#24]
This is a 'nice to have', but since MAME requires save states to be created on the same version of the emulator that they are loaded on, it's a bit of a pain that emularity's drivers are different versions - it means I need to make ZX Spectrum saves in 0.177, and Atari saves in 0.187, and so on. It would be cool if they were all on the same version.

**Comment by db48x** [comment]
I think we've actually got this mostly sorted out. I've got a build machine that can crank out all of the builds in a day or two with not a whole lot of hand-holding, and we've used it a number of times to upgrade all of the emulators hosted on archive.org.

I'm pretty sure we're still at least one version behind (again), but at least they're all the same version now.

**Comment by bfod** [comment]
Oh sweet! Thanks for the heads up.
