### ISSUE TITLE
Mounting the archive as a CD ROM drive (DosBox)

### ISSUE THREAD

**Issue by ahtoh68** [db48x/emularity#26]
In the emulator it is possible to mount the archive as a CD ROM drive?
Is there a solution for such tasks?

**Comment by db48x** [comment]
Yes, you can mount an ISO. Simply use `mountFile` as normal to download the ISO file, then use `extraArgs` to give DosBox an `imgmount` command using that ISO (http://www.dosbox.com/wiki/IMGMOUNT).

For example:

    new DosBoxLoader(DosBoxLoader.mountFile("example.iso",
                                            DosBoxLoader.fetchFile("Game File",
                                                                   "path/to/example.iso")),
                     DosBoxLoader.extraArgs(["-c", "imgmount d /emulator/example.iso -t iso"]),

**Comment by ahtoh68** [comment]
In the console makes an error:
`Uncaught TypeError: DosBoxLoader.extraArgs is not a function`

As far as I can judge from the information TECHNICAL.md, the extraArgs function is only applicable for working with the emulatorJSMESS:

> MMAME
MAMELoader.driver(driverName)
MAMELoader.extraArgs(args)
MAMELoader.peripheral(name, filename)
JSMESS
JSMESSLoader is merely a synonym for MAMELoader, and is provided so that we don't break existing users.

And in the file loader.js I did not find the function extraArgs, which interacts with dosbox. Perhaps I have an outdated version. Despite the fact that I use files from this repository.

**Comment by ahtoh68** [comment]
Does not want to process the command "imgmount d /emulator/example.iso -t iso"
My code looks like this:
```
var emulator = new Emulator(document.querySelector("#canvas"),
	null,
	new DosBoxLoader(DosBoxLoader.emulatorJS("emulators/em-dosbox/dosbox-sync.js"),
		DosBoxLoader.locateAdditionalEmulatorJS(locateAdditionalFiles),
		DosBoxLoader.nativeResolution(640, 400),
		DosBoxLoader.mountZip("c",
				DosBoxLoader.fetchFile("Game File",
							"examples/base/bd.zip")),
		DosBoxLoader.mountFile("bdcd.iso",
				DosBoxLoader.fetchFile("Game File",
							"examples/base/bdcd.iso")),
				DosBoxLoader.extraArgs(["-c", "imgmount d /emulator/bdcd.iso -t iso"]),
		DosBoxLoader.startExe("START.BAT")))
	emulator.start({ waitAfterDownloading: false});

function locateAdditionalFiles(filename) {
	if (filename === "dosbox.html.mem") {
		return "emulators/em-dosbox/dosbox-sync.mem";
	}
	return "emulators/em-dosbox/"+ filename;
}
```
DOSBOX  prints this code to me:
Z:\mount undefined /emulatorbdcd.iso
photo errors: [https://i.imgur.com/8bxfjkS.png](url)

**Comment by db48x** [comment]
Nice, you found another interesting bug. I've pushed a fix; let me know how it goes.

**Comment by ahtoh68** [comment]
Many thanks !!! Everything works fine !!!

**Comment by t0mii** [comment]
hello, in dosbox i get following error after imgmount my iso file
MSCDEX: Failure: Not yet supported.
may u have any advice?

**Comment by leimao** [comment]
This looks cool.
