### ISSUE TITLE
keyevent() in Chrome/IE

### ISSUE THREAD

**Issue by bengarrett** [db48x/emularity#5]
I found the prevention of the space bar scrolling behaviour doesn't work in Google Chrome or IE.

I updated the function with a solution from Stack and it seems to work http://stackoverflow.com/questions/18522864/disable-scroll-down-when-spacebar-is-pressed-on-firefox

```
// stashes these event listeners so that we can remove them after
                window.addEventListener('keydown', k = keyevent(resolve));
```

```
    function keyevent(resolve) {
      return function(e) {
        if ((e.keycode || e.which) == 32) {
          e.preventDefault();
          resolve();
        }
      };
    };
```

**Comment by db48x** [comment]
Hmm; what version are you testing in? It works for me in Chrome 51 and IE 11.

**Comment by bengarrett** [comment]
I am using Chrome 49 & IE 11.1 on Win 10.

**Comment by bengarrett** [comment]
Hmm turns out it must be a plugin or addon conflict. As when I run in incognito mode (where none are loaded) there doesn't seem to be an issue. Sorry about that.

**Comment by db48x** [comment]
Ah! I didn't expect an incompatibility with an addon, but I'll remember it for the future. Thanks for double checking. :)
