### ISSUE TITLE
cpc6128.json has a wrong native_resolution values

### ISSUE THREAD

**Issue by nonom** [db48x/emularity#64]
i don't know if its the right place, sorry in advance.

The native_resolution in cpc6128.json is wrong -at least the height-
https://git.archive.org/db48x/emularity_engine_v1/blob/master/cpc6128.json
The measures have more sense here (check both native_resolution parameters)
https://git.archive.org/db48x/emularity_engine_v1/blob/master/cpc464.json

It causes the following problem running emularity as default.
https://archive.org/details/amstrad_abadia_del_crimen_64

By other side, Would nice if you know about how to pass the extra_args arguments into Archive.org in any meta tag because it's lack of examples.
The wiki seems obsolete since no reflect this emulator, seems the only popular old computer missing. Which is sad.

Proof and error is the only I have.

In archive,org forums they redirect me to info@archive.org but nobody answered since a week. I hope to have luck in anyway.

**Comment by nonom** [comment]
Here are the measurements of the pixelable area of ​​the CTM644 screen for the next one that needs them (width x height):

Aspect Ratio: 4: 3

External edge (up to plastic), 286mm x 208mm (diagonal of the rectangle would be 353.63mm = 13.93 ")
Actual diagonal (rounded corners): 340mm = 13.38 "
Edge thickness: 46mm (23mm + 23mm) and 58mm (29mm + 29mm)

Internal area: 240mm x 150mm (diagonal would be 283mm = 11.14 ")

It's applicable for CPC464 and CPC 6128

**Comment by db48x** [comment]
That does look like an unlikely resolution. As you suspected, this isn't technically the right place for this kind of bug report, but I'm the right person to take care of it. I'll make sure the folks who read the questions sent to info@archive.org know to forward this kind of thing to me.

I'll double-check the resolution that MAME lists as the native resolution for these systems and then update the JSON files to match.

**Comment by db48x** [comment]
MAME actually lists 704×144 as the native resolution, but I went ahead and changed it to 704×576. I don't think this is exactly correct, but it is at least usable.

**Comment by db48x** [comment]
Oh, and for your other question: we don't currently have a way to specify extra arguments in the item metadata. We've generally been adding new json files for common variations.

**Comment by nonom** [comment]
I saw your commits, really thanks to open the doors of Emularity to the Amstrad CPC world. We still doing cpc games for fun.  Thank  you very much in the name of the community.

The real measures from the colour screen are:

- External borded (plastic included :), 208mm x 286mm
- Internal Area: 150 x 240 mm which is probably the best choice.

As you can see the borders are so bigger while the screen size should be much like the zx spectrum.

Anyways , thanks and let's close this ticket. Thanks again
