### ISSUE TITLE
JSMAME web audio code no longer needed

### ISSUE THREAD

**Issue by DopefishJustin** [db48x/emularity#7]
The JSMAME web audio code is now in the MAME source tree at https://github.com/mamedev/mame/blob/master/src/osd/modules/sound/js_sound.js and compiled into the mame______.js.gz files, so setup_jsmame_webaudio() is dead code and no longer needs to be in loader.js. This happened several version cycles ago so there should be nothing left on archive.org depending on it.

**Comment by taisel** [comment]
Last I checked mame still doesn't query the sample count remaining. I forgot if mame queries the web audio sample rate either so 44100 isn't assumed.

**Comment by db48x** [comment]
Nice. We query the sample rate as a separate step at the moment, so we can remove one without the other. I'd really like to get rid of the sample rate query though, as it creates a useless extra audio context that can't be disposed of, and there's only so many of those that you can have hanging around.

**Comment by taisel** [comment]
The bigger issue being the lack of proper buffering logic MAME is conducting.

**Comment by db48x** [comment]
Sweet. With this change https://archive.org/details/sg_Sonic_the_Hedgehog_Rev_1_1991_Sega_JP-KR_en&external_js=1 doesn't glitch at all in the attract screen (unless it's in a background tab).

**Comment by db48x** [comment]
Thanks guys!

**Comment by DopefishJustin** [comment]
taisel: Yeah I know, I've tried some experiments in that direction but the sound is now to a point where it honestly sounds fine most of the time and it's hard to tell if changes are actually helping or not. I'm also pretty out of my element with this stuff.

**Comment by taisel** [comment]
It's guessing the correct output rate, but it's not actually checking for under/overflow. Hence, why it seems correct at first glance.
