### ISSUE TITLE
Trying to setup arcade example

### ISSUE THREAD

**Issue by orangewhipster** [db48x/emularity#72]
Love this project! Tried it out many times on archive.org but would like to implement it myself for a little project Im working on.

Without documentation, I just went in a tried to do the arcade example. It sees the file, but then can't load the exidy emulator. I take it the emulator goes inside the jsmess folder? Is something supposed t be compiled?  Looking at the dev tools in Chrome it says it can't find the mameexidy.wasm file?

Cheers!

**Comment by db48x** [comment]
That's correct. None of the files for the examples are a part of this repository; instead, each example documents where to download them from the Internet Archive.
