### ISSUE TITLE
Cannot run the arcade example: jsmess_set_mastervolume reference error on messexidy.js

### ISSUE THREAD

**Issue by alexandretorres** [db48x/emularity#8]
Hi, I was trying the emularity Mame example "example_aracade".
I downloaded messexidy.js.gz (the git-annex was not working for this file) and the targ.zip
I also added an undocumented gofullscreen element to the html.
But this error I could not solve. I think that something was added on Mame and was not updated at emularity:

ReferenceError: jsmess_set_mastervolume is not defined
http://localhost/emulators/jsmess/messexidy.js line 407 > eval
Line 1
 
Thanks for the project, I hope you continue. I´d like to share a few programs developed on an old coco2 to friends :)

**Comment by db48x** [comment]
I can't reproduce this. I've checked the mameexidy.js file on archive.org, and as I expected it has a jsmame_set_mastervolume function, not jsmess_set_mastervolume. It's not immediately obvious why you would get this error message. Even if you got an old version of the file with the older function name, it would still be internally consistent...

Could you double-check this, and get a stack trace for the error? That should clarify the matter.

**Comment by alexandretorres** [comment]
mameexidy.js? this is not the same as messexidy.  Ok, I saw the new fix :) 
I will try this one. Notice that the comments of the arcade are still pointing to messexidy.js.gz at archive.org. I guess we should avoid all mess*.js and use the mame*.js versions, alright?

version ref: 
https://github.com/db48x/emularity/commit/6086f2c80abd65eaa21bcdc30113c5660a499b9a

Thanks

**Comment by alexandretorres** [comment]
Now it works! :)
just downloaded the correct js from : https://archive.org/download/emularity_engine_v1/mameexidy.js.gz
and dl the new version of example_arcade.
Thanks!

**Comment by db48x** [comment]
Ohhh, I see what happened. Since MESS and MAME have been officially combined into a single project under the MAME name, when @textfiles recompiled all of the emulators he changed the names to use the 'mame' prefix instead of a mix of 'mess' and 'mame'. Unfortunately he left the original files in place to cause confusion. Fun!

I'll fix the comments in the example as well.

**Comment by bfod** [comment]
The Atari 2600 example fails on this front too. The jsmame archive doesn't have a messa2600.js file, and if I try to load in the one from the older jsmess archive I get the same error in "jsmess_set_mastervolume"

**Comment by db48x** [comment]
But it does have a mamea2600.js, which is what the example calls for. https://archive.org/download/emularity_engine_v1/mamea2600.js.gz

**Comment by bfod** [comment]
ah cool, thanks. I got messed up by the example html file, which points to:
(https://archive.org/download/emularity_engine_jsmame/messa2600.js.gz) 
which doesn't exist anymore.

**Comment by db48x** [comment]
Oops, I never actually changed the comments. (and the annexed files are also woefully out of date, but I'm actually working on that)
