### ISSUE TITLE
Emulator freezes when loading machine

### ISSUE THREAD

**Issue by Aiden-M-C** [db48x/emularity#92]
I recently got Example_arcade.html working on a server I'm running off a raspberry PI. I then started to try and run other ROMS the first one I tried was Out Run and it works perfectly. I then tried to run Street Fighter Alpha 2, the game files and WASM binary load, however, when I launch the emulator I get a text box on screen saying "Loading Machine (80%)" and it stays like that forever. The same happens with Alpha 3, Metal Slug 2 and Killer Instinct. I am very new to this so I'm unsure if this is happening due to something I missed or if it's because I'm running it from a raspberry PI and the games are too large for it. Any help would be greatly appreciated.

this is the HTML I'm using.

==================================================================================
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>ALPHA 2</title>
  </head>
  <body>
    <canvas id="canvas" style="width: 50%; height: 50%; display: block; margin: 0 auto;"></canvas>
    <script type="text/javascript" src="es6-promise.js"></script>
    <script type="text/javascript" src="browserfs.min.js"></script>
    <script type="text/javascript" src="loader.js"></script>
    <script type="text/javascript">
      var emulator = new Emulator(document.querySelector("#canvas"),
                                  null,
                                  new MAMELoader(MAMELoader.driver("sfa2"),
                                                   MAMELoader.nativeResolution(384, 224),
                                                   MAMELoader.scale(3),
						   MAMELoader.emulatorWASM("emulators/jsmess/mamecps2.wasm"),
                                                   MAMELoader.emulatorJS("emulators/jsmess/mamecps2.js"),
                                                   MAMELoader.mountFile("sfa2.zip",
                                                                          JSMAMELoader.fetchFile("Game File",
                                                                                                 "examples/sfa2.zip"))))
      emulator.start({ waitAfterDownloading: true });
    </script>
  </body>
</html>
==================================================================================

Little update, I have since tried Street Fighter 2, Ghost 'n Goblins, and Super Punch Out thinking that its smaller size may work if the issue is due to the PI however, for SF2 and GnG the "Loading Machine" text box never appears the screen just remains black. SPO works fine though. 

Also, I'm not sure if this is helpful information at all but, I have gotten Alpha 2 & 3 to work using IALoader but I would prefer to have things running from just the PI itself if at all possible.

**Comment by db48x** [comment]
Sounds like a problem with the emulator, which in this case is MAME. It could also be a problem with your browser, or the amount of memory available to your browser. Are you running the browser on the Rasberry Pi, or on a normal computer?

**Comment by Aiden-M-C** [comment]
> Sounds like a problem with the emulator, which in this case is MAME. It could also be a problem with your browser, or the amount of memory available to your browser. Are you running the browser on the Rasberry Pi, or on a normal computer?

Thank you for the response. to answer your question I'm using firefox on a windows laptop, I've also tried chrome on a more powerful desktop PC and it has the same result. Is there a way to check to see if the problem is with MAME or do you have any suggestions to try and fix the issue?

**Comment by db48x** [comment]
Aside from checking the developer tools to see if MAME is printing any error messages or throwing an exception, no.

**Comment by Aiden-M-C** [comment]
> Aside from checking the developer tools to see if MAME is printing any error messages or throwing an exception, no.

oh sweet I'll look into that sorry if that's obvious I'm really new to all this. Thanks again for the help.
